#!/usr/bin/env python3
"""
gen_fit_its.py — Dynamic FIT ITS generator for RK3576 UEFI boot chain.

Reads actual PT_LOAD segment addresses from BL31 ELF and generates a
correct .its file.  Eliminates the "copy-paste RK3588 address" class of bugs.

Usage:
    python3 gen_fit_its.py <pkgdir> <device> <bl31_entry_hex>

    pkgdir       : directory containing BL33_AP_UEFI.Fv, bl31_0x*.bin,
                   bl32.bin, <device>.dtb
    device       : e.g. rk3576-rock-4d
    bl31_entry_hex: BL31 entry point from ELF e_entry, e.g. 0x40040000

The entry point is the paddr of atf-1 (main code segment), which SPL/BL31
uses as the firmware entry in the FIT configuration node.

BL33 (EDK2) load address defaults to 0x40800000, matching
  plat/rockchip/rk3576/platform.mk: BL33_BASE := 0x40800000
"""

import os
import sys
import glob


BL33_LOAD_ADDR = 0x40800000   # Must match TF-A BL33_BASE
OPTEE_LOAD_ADDR = 0x08400000


def discover_bl31_segs(pkgdir: str) -> list[tuple[int, str]]:
    """Return sorted list of (paddr, filepath) for all bl31_0x*.bin files."""
    pattern = os.path.join(pkgdir, "bl31_0x*.bin")
    segs = []
    for path in glob.glob(pattern):
        basename = os.path.basename(path)
        # basename = "bl31_0x3fe70000.bin"
        hex_part = basename[len("bl31_0x"):basename.index(".bin")]
        paddr = int(hex_part, 16)
        segs.append((paddr, path))
    segs.sort(key=lambda x: x[0])
    return segs


def make_atf_node(idx: int, paddr: int, filename: str, entry: int | None) -> str:
    desc_map = {
        0x3fe70000: "PMUSRAM",
        0x40040000: "main code + entry",
        0x4005d000: "coherent data",
        0x40060000: "main code + entry (vendor BL31)",
        0x400f0000: "coherent data (vendor BL31)",
    }
    desc = desc_map.get(paddr, f"segment @{paddr:#010x}")
    lines = [
        f"\t\tatf-{idx} {{",
        f'\t\t\tdescription = "ARM Trusted Firmware BL31 ({desc})";',
        f'\t\t\tdata = /incbin/("./{filename}");',
        f'\t\t\ttype = "firmware";',
        f'\t\t\tarch = "arm64";',
        f'\t\t\tos = "arm-trusted-firmware";',
        f'\t\t\tcompression = "none";',
        f"\t\t\tload = <{paddr:#010x}>;",
    ]
    if entry is not None:
        lines.append(f"\t\t\tentry = <{entry:#010x}>;")
    lines += [
        "\t\t\thash {",
        '\t\t\t\talgo = "sha256";',
        "\t\t\t};",
        "\t\t};",
    ]
    return "\n".join(lines)


def generate(pkgdir: str, device: str, bl31_entry: int) -> str:
    segs = discover_bl31_segs(pkgdir)
    if not segs:
        raise RuntimeError(f"No bl31_0x*.bin files found in {pkgdir}")

    # Sort: PMUSRAM (lowest paddr) first as atf-1, with entry pointing at
    # the main code segment. This matches Rockchip make_fit_atf.py /
    # mainline U-Boot's working FIT layout exactly. Putting the main code
    # segment as atf-1 has empirically produced atf-3 SHA256 errors in SPL
    # — likely because spl_load_simple_fit's load order or buffer reuse
    # depends on the conventional [PMUSRAM, MAIN, COHERENT] layout.
    ordered_segs = sorted(segs, key=lambda x: x[0])

    atf_nodes = []
    atf_names = []
    for i, (paddr, fpath) in enumerate(ordered_segs, start=1):
        fname = os.path.basename(fpath)
        # entry annotation goes on the FIRST atf node (firmware), regardless
        # of which segment owns the entry point — SPL uses configuration's
        # firmware = "atf-1" and reads its `entry` property as jump target.
        entry = bl31_entry if i == 1 else None
        atf_nodes.append(make_atf_node(i, paddr, fname, entry))
        atf_names.append(f"atf-{i}")

    # firmware = atf-1 (entry point segment); loadables = rest
    # Order matches working u-boot.itb: BL33 first, then ATF tail segments.
    # Empty op-tee stub omitted — SPL hash check on data-size=0 is brittle.
    # IMPORTANT: load small ATF segments BEFORE the 5MB EDK2 BL33. Loading
    # 5MB via SFC DMA before tiny segments has been observed to leave the
    # SFC controller / SPL state in a way that corrupts subsequent reads
    # of small (<64B-tail) segments → atf-3 hash error.
    loadables_no_nvdata = atf_names[1:] + ["edk2"]

    its = f"""/dts-v1/;
/* Auto-generated by gen_fit_its.py — do not edit manually */

/ {{
\tdescription = "FIT Image with ATF/OP-TEE/UEFI for RK3576 ({device})";
\t#address-cells = <1>;

\timages {{
"""
    for node in atf_nodes:
        its += node + "\n"

    its += f"""\t\tfdt {{
\t\t\tdescription = "SPL DTB";
\t\t\tdata = /incbin/("./{device}.dtb");
\t\t\ttype = "flat_dt";
\t\t\tarch = "arm64";
\t\t\tcompression = "none";
\t\t\thash {{
\t\t\t\talgo = "sha256";
\t\t\t}};
\t\t}};
\t\tedk2 {{
\t\t\tdescription = "EDK2 UEFI Firmware (BL33)";
\t\t\tdata = /incbin/("./BL33_AP_UEFI.Fv");
\t\t\ttype = "firmware";
\t\t\tarch = "arm64";
\t\t\tos = "u-boot";
\t\t\tcompression = "none";
\t\t\tload = <{BL33_LOAD_ADDR:#010x}>;
\t\t\tentry = <{BL33_LOAD_ADDR:#010x}>;
\t\t}};
\t}};

\tconfigurations {{
\t\tdefault = "conf";
\t\tconf {{
\t\t\tdescription = "{device}";
\t\t\trollback-index = <0x0>;
\t\t\tfirmware = "{atf_names[0]}";
\t\t\tloadables = {", ".join('"' + n + '"' for n in loadables_no_nvdata)};
\t\t\tfdt = "fdt";
\t\t}};
\t}};
}};
"""
    return its


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)

    pkgdir, device, entry_str = sys.argv[1], sys.argv[2], sys.argv[3]
    bl31_entry = int(entry_str, 16)

    its_text = generate(pkgdir, device, bl31_entry)
    out_path = os.path.join(pkgdir, f"{device}_EFI.its")
    with open(out_path, "w") as f:
        f.write(its_text)

    print(f"Generated: {out_path}")
    segs = discover_bl31_segs(pkgdir)
    print(f"BL31 segments ({len(segs)}):")
    for paddr, fpath in segs:
        sz = os.path.getsize(fpath)
        print(f"  {paddr:#010x}  {os.path.basename(fpath)}  ({sz} bytes)")
    print(f"EDK2 load: {BL33_LOAD_ADDR:#010x}")
    print(f"BL31 entry: {bl31_entry:#010x}")
